package Tipo_clienteApp;


/**
* Tipo_clienteApp/Tipo_clienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tipo_cliente.idl
* sábado 11 de mayo de 2019 10:31:13 PM COT
*/

public interface Tipo_clienteOperations 
{
  boolean insertarTipo_cliente (String tipo);
  boolean actualizarTipo_cliente (String tipo);
  boolean eliminarTipo_cliente (int id_tipo);
  void shutdown ();
} // interface Tipo_clienteOperations
