package Tipo_clienteApp;


/**
* Tipo_clienteApp/Tipo_cliente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tipo_cliente.idl
* sábado 11 de mayo de 2019 10:31:13 PM COT
*/

public interface Tipo_cliente extends Tipo_clienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Tipo_cliente
