package ProveedoresApp;


/**
* ProveedoresApp/ProveedoresOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from proveedores.idl

*/

public interface ProveedoresOperations 
{
  boolean insertarProveedores (int cedula, String nombre, String apellido, String telefono, int id_producto, int id_marca, int marca, int precio_compra);
  boolean actualizarProveedores (int cedula, String nombre, String apellido, String telefono, int id_producto, int id_marca, int marca, int precio_compra);
  boolean eliminarProveedores (int id);
  void shutdown ();
} // interface ProveedoresOperations
