package ProveedoresApp;


/**
* ProveedoresApp/Proveedores.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from proveedores.idl

*/

public interface Proveedores extends ProveedoresOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Proveedores
