package Principal;



import cliente.TipoCliente;
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Felipe Gutierrez
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.getContentPane().setBackground(Color.darkGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        btnAdministrador = new javax.swing.JButton();
        btnBanco = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        bntFacturacion = new javax.swing.JButton();
        btnInformacion = new javax.swing.JButton();
        btnLocal = new javax.swing.JButton();
        btnMarca = new javax.swing.JButton();
        btnPendiente = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnSueldo = new javax.swing.JButton();
        btnTipoCliente = new javax.swing.JButton();
        btnTipoPago = new javax.swing.JButton();
        btnTrabajador = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdministrador.setBackground(new java.awt.Color(0, 153, 153));
        btnAdministrador.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministrador.setText("ADMINISTRADOR");
        btnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorActionPerformed(evt);
            }
        });

        btnBanco.setBackground(new java.awt.Color(0, 153, 153));
        btnBanco.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnBanco.setForeground(new java.awt.Color(255, 255, 255));
        btnBanco.setText("BANCO");
        btnBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBancoActionPerformed(evt);
            }
        });

        btnCliente.setBackground(new java.awt.Color(0, 153, 153));
        btnCliente.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCliente.setText("CLIENTE");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        bntFacturacion.setBackground(new java.awt.Color(0, 153, 153));
        bntFacturacion.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        bntFacturacion.setForeground(new java.awt.Color(255, 255, 255));
        bntFacturacion.setText("FACTURACION");
        bntFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntFacturacionActionPerformed(evt);
            }
        });

        btnInformacion.setBackground(new java.awt.Color(0, 153, 153));
        btnInformacion.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnInformacion.setForeground(new java.awt.Color(255, 255, 255));
        btnInformacion.setText("INFORMACION");
        btnInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionActionPerformed(evt);
            }
        });

        btnLocal.setBackground(new java.awt.Color(0, 153, 153));
        btnLocal.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnLocal.setForeground(new java.awt.Color(255, 255, 255));
        btnLocal.setText("LOCAL");
        btnLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalActionPerformed(evt);
            }
        });

        btnMarca.setBackground(new java.awt.Color(0, 153, 153));
        btnMarca.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnMarca.setForeground(new java.awt.Color(255, 255, 255));
        btnMarca.setText("MARCA");
        btnMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcaActionPerformed(evt);
            }
        });

        btnPendiente.setBackground(new java.awt.Color(0, 153, 153));
        btnPendiente.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnPendiente.setForeground(new java.awt.Color(255, 255, 255));
        btnPendiente.setText("PENDIENTE");
        btnPendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendienteActionPerformed(evt);
            }
        });

        btnProducto.setBackground(new java.awt.Color(0, 153, 153));
        btnProducto.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnProducto.setText("PRODUCTO");
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });

        btnProveedor.setBackground(new java.awt.Color(0, 153, 153));
        btnProveedor.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedor.setText("PROVEEDORES");
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });

        btnSueldo.setBackground(new java.awt.Color(0, 153, 153));
        btnSueldo.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnSueldo.setForeground(new java.awt.Color(255, 255, 255));
        btnSueldo.setText("SUELDO");
        btnSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSueldoActionPerformed(evt);
            }
        });

        btnTipoCliente.setBackground(new java.awt.Color(0, 153, 153));
        btnTipoCliente.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnTipoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnTipoCliente.setText("TIPOS DE CLIENTE");
        btnTipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoClienteActionPerformed(evt);
            }
        });

        btnTipoPago.setBackground(new java.awt.Color(0, 153, 153));
        btnTipoPago.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnTipoPago.setForeground(new java.awt.Color(255, 255, 255));
        btnTipoPago.setText("TIPOS DE PAGO");
        btnTipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoPagoActionPerformed(evt);
            }
        });

        btnTrabajador.setBackground(new java.awt.Color(0, 153, 153));
        btnTrabajador.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        btnTrabajador.setText("TRABAJADORES");
        btnTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajadorActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(0, 153, 153));
        btnLogin.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("REGISTRO DE VENTAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntFacturacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPendiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLocal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTrabajador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSueldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTipoPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTipoCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdministrador)
                    .addComponent(btnLocal)
                    .addComponent(btnSueldo))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBanco)
                    .addComponent(btnMarca)
                    .addComponent(btnTipoCliente))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCliente)
                    .addComponent(btnPendiente)
                    .addComponent(btnTipoPago))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntFacturacion)
                    .addComponent(btnProducto)
                    .addComponent(btnTrabajador))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInformacion)
                    .addComponent(btnProveedor)
                    .addComponent(btnLogin))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorActionPerformed
        administrador.RegistroAdministrador objAdministrador = new administrador.RegistroAdministrador();
        objAdministrador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdministradorActionPerformed

    private void btnBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBancoActionPerformed
        banco.RegistroBanco objBanco = new banco.RegistroBanco();
        objBanco.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBancoActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        cliente.RegistroCliente objCliente = new cliente.RegistroCliente();
        objCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnClienteActionPerformed

    private void bntFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntFacturacionActionPerformed
       facturacion.RegistroFacturacion objFacturacion = new facturacion.RegistroFacturacion();
       objFacturacion.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_bntFacturacionActionPerformed

    private void btnInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionActionPerformed
        informacion.RegistroInformacion objInformacion = new informacion.RegistroInformacion();
        objInformacion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInformacionActionPerformed

    private void btnLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalActionPerformed
        local.RegistroLocal objLocal = new local.RegistroLocal();
        objLocal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLocalActionPerformed

    private void btnMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcaActionPerformed
        marca.RegistroMarca objMarca = new marca.RegistroMarca();
        objMarca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMarcaActionPerformed

    private void btnPendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendienteActionPerformed
       pendiente.RegistroPendiente objFacturacion = new pendiente.RegistroPendiente();
       objFacturacion.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnPendienteActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        productos.RegistroProducto objProducto = new productos.RegistroProducto();
        objProducto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        proveedores.RegistroProveedores objProveedores = new proveedores.RegistroProveedores();
        objProveedores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSueldoActionPerformed
        sueldo.registroSueldo objSueldo = new sueldo.registroSueldo();
        objSueldo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSueldoActionPerformed

    private void btnTipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoClienteActionPerformed
        tipo_cliente.RegistroTipo_cliente objTipoCliente = new tipo_cliente.RegistroTipo_cliente();
        objTipoCliente.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_btnTipoClienteActionPerformed

    private void btnTipoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoPagoActionPerformed
    tipo_pago.RegristroTipoPago objTipoPago  = new  tipo_pago.RegristroTipoPago();
    objTipoPago.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnTipoPagoActionPerformed

    private void btnTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajadorActionPerformed
        trabajadores.registro_trabajador objTrabajador = new trabajadores.registro_trabajador();
        objTrabajador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTrabajadorActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        login.RegistroLogin objLogin = new login.RegistroLogin();
        objLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntFacturacion;
    private javax.swing.JButton btnAdministrador;
    private javax.swing.JButton btnBanco;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnInformacion;
    private javax.swing.JButton btnLocal;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMarca;
    private javax.swing.JButton btnPendiente;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnSueldo;
    private javax.swing.JButton btnTipoCliente;
    private javax.swing.JButton btnTipoPago;
    private javax.swing.JButton btnTrabajador;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
