package SueldoApp;


/**
* SueldoApp/SueldoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sueldo.idl
* lunes 20 de mayo de 2019 08:00:30 PM COT
*/

public interface SueldoOperations 
{
  boolean insertarSueldo (int sueldo, String estado);
  boolean actualizarSueldo (int sueldo, String estado);
  boolean eliminarSueldo (int id_trabajador);
  void shutdown ();
} // interface SueldoOperations
