package SueldoApp;


/**
* SueldoApp/Sueldo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sueldo.idl
* lunes 20 de mayo de 2019 08:00:30 PM COT
*/

public interface Sueldo extends SueldoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sueldo
