package SueldoApp;


/**
* SueldoApp/SueldoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sueldo.idl
* martes 21 de mayo de 2019 14H41' COT
*/

public interface SueldoOperations 
{
  boolean insertarSueldo (int sueldo, String estado, int id_trabajador);
  boolean actualizarSueldo (int sueldo, String estado, int id_trabajador);
  boolean eliminarSueldo (int id);
  void shutdown ();
} // interface SueldoOperations
