package LoginApp;


/**
* LoginApp/loginHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from login.idl
* viernes 17 de mayo de 2019 09:53:45 PM COT
*/

abstract public class loginHelper
{
  private static String  _id = "IDL:LoginApp/login:1.0";

  public static void insert (org.omg.CORBA.Any a, LoginApp.login that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LoginApp.login extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (LoginApp.loginHelper.id (), "login");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LoginApp.login read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_loginStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LoginApp.login value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static LoginApp.login narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LoginApp.login)
      return (LoginApp.login)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LoginApp._loginStub stub = new LoginApp._loginStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static LoginApp.login unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LoginApp.login)
      return (LoginApp.login)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LoginApp._loginStub stub = new LoginApp._loginStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
