package LoginApp;


/**
* LoginApp/login.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from login.idl
* viernes 17 de mayo de 2019 09:53:45 PM COT
*/

public interface login extends loginOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface login
