package LoginApp;


/**
* LoginApp/loginOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from login.idl
* lunes 20 de mayo de 2019 07:02:15 PM COT
*/

public interface loginOperations 
{
  boolean insertarLogin (String usuario, String contrasena);
  boolean actualizarLogin (String usuario, String contrasena);
  boolean eliminarLogin (int id);
  void shutdown ();
} // interface loginOperations
