package LoginApp;


/**
* LoginApp/login.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from login.idl
* lunes 20 de mayo de 2019 07:02:15 PM COT
*/

public interface login extends loginOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface login
